// <auto-generated>
//  !! WARNING !! This file is auto-generated. Changes to this file will be lost.
// </auto-generated>


using SapNwRfc.Internal.Interop;

namespace SapNwRfc.Exceptions
{
    public enum SapErrorGroup
    {
        UnknownValue = -1,
        Ok,
        AbapApplicationFailure,
        AbapRuntimeFailure,
        LogonFailure,
        CommunicationFailure,
        ExternalRuntimeFailure,
        ExternalApplicationFailure,
        ExternalAuthorizationFailure,
    }

    internal static class SapErrorGroupMapper
    {
        public static SapErrorGroup Map(RfcErrorGroup errorGroup)
        {
            switch (errorGroup)
            {
            case RfcErrorGroup.OK: return SapErrorGroup.Ok;
            case RfcErrorGroup.ABAP_APPLICATION_FAILURE: return SapErrorGroup.AbapApplicationFailure;
            case RfcErrorGroup.ABAP_RUNTIME_FAILURE: return SapErrorGroup.AbapRuntimeFailure;
            case RfcErrorGroup.LOGON_FAILURE: return SapErrorGroup.LogonFailure;
            case RfcErrorGroup.COMMUNICATION_FAILURE: return SapErrorGroup.CommunicationFailure;
            case RfcErrorGroup.EXTERNAL_RUNTIME_FAILURE: return SapErrorGroup.ExternalRuntimeFailure;
            case RfcErrorGroup.EXTERNAL_APPLICATION_FAILURE: return SapErrorGroup.ExternalApplicationFailure;
            case RfcErrorGroup.EXTERNAL_AUTHORIZATION_FAILURE: return SapErrorGroup.ExternalAuthorizationFailure;
            default: return SapErrorGroup.UnknownValue;
            }
        }
    }
}
