// <auto-generated>
//  !! WARNING !! This file is auto-generated. Changes to this file will be lost.
// </auto-generated>


using System.Diagnostics.CodeAnalysis;
using SapNwRfc.Internal.Interop;

namespace SapNwRfc.Exceptions
{
    public enum SapResultCode
    {
        UnknownValue = -1,
        Ok,
        CommunicationFailure,
        LogonFailure,
        AbapRuntimeFailure,
        AbapMessage,
        AbapException,
        Closed,
        Canceled,
        Timeout,
        MemoryInsufficient,
        VersionMismatch,
        InvalidProtocol,
        SerializationFailure,
        InvalidHandle,
        Retry,
        ExternalFailure,
        Executed,
        NotFound,
        NotSupported,
        IllegalState,
        InvalidParameter,
        CodepageConversionFailure,
        ConversionFailure,
        BufferTooSmall,
        TableMoveBof,
        TableMoveEof,
        StartSapGuiFailure,
        AbapClassException,
        UnknownError,
        AuthorizationFailure,
        RcMaxValue,
    }

    [ExcludeFromCodeCoverage]
    internal static class SapResultCodeMapper
    {
        public static SapResultCode Map(RfcResultCode resultCode)
        {
            switch (resultCode)
            {
            case RfcResultCode.RFC_OK: return SapResultCode.Ok;
            case RfcResultCode.RFC_COMMUNICATION_FAILURE: return SapResultCode.CommunicationFailure;
            case RfcResultCode.RFC_LOGON_FAILURE: return SapResultCode.LogonFailure;
            case RfcResultCode.RFC_ABAP_RUNTIME_FAILURE: return SapResultCode.AbapRuntimeFailure;
            case RfcResultCode.RFC_ABAP_MESSAGE: return SapResultCode.AbapMessage;
            case RfcResultCode.RFC_ABAP_EXCEPTION: return SapResultCode.AbapException;
            case RfcResultCode.RFC_CLOSED: return SapResultCode.Closed;
            case RfcResultCode.RFC_CANCELED: return SapResultCode.Canceled;
            case RfcResultCode.RFC_TIMEOUT: return SapResultCode.Timeout;
            case RfcResultCode.RFC_MEMORY_INSUFFICIENT: return SapResultCode.MemoryInsufficient;
            case RfcResultCode.RFC_VERSION_MISMATCH: return SapResultCode.VersionMismatch;
            case RfcResultCode.RFC_INVALID_PROTOCOL: return SapResultCode.InvalidProtocol;
            case RfcResultCode.RFC_SERIALIZATION_FAILURE: return SapResultCode.SerializationFailure;
            case RfcResultCode.RFC_INVALID_HANDLE: return SapResultCode.InvalidHandle;
            case RfcResultCode.RFC_RETRY: return SapResultCode.Retry;
            case RfcResultCode.RFC_EXTERNAL_FAILURE: return SapResultCode.ExternalFailure;
            case RfcResultCode.RFC_EXECUTED: return SapResultCode.Executed;
            case RfcResultCode.RFC_NOT_FOUND: return SapResultCode.NotFound;
            case RfcResultCode.RFC_NOT_SUPPORTED: return SapResultCode.NotSupported;
            case RfcResultCode.RFC_ILLEGAL_STATE: return SapResultCode.IllegalState;
            case RfcResultCode.RFC_INVALID_PARAMETER: return SapResultCode.InvalidParameter;
            case RfcResultCode.RFC_CODEPAGE_CONVERSION_FAILURE: return SapResultCode.CodepageConversionFailure;
            case RfcResultCode.RFC_CONVERSION_FAILURE: return SapResultCode.ConversionFailure;
            case RfcResultCode.RFC_BUFFER_TOO_SMALL: return SapResultCode.BufferTooSmall;
            case RfcResultCode.RFC_TABLE_MOVE_BOF: return SapResultCode.TableMoveBof;
            case RfcResultCode.RFC_TABLE_MOVE_EOF: return SapResultCode.TableMoveEof;
            case RfcResultCode.RFC_START_SAP_GUI_FAILURE: return SapResultCode.StartSapGuiFailure;
            case RfcResultCode.RFC_ABAP_CLASS_EXCEPTION: return SapResultCode.AbapClassException;
            case RfcResultCode.RFC_UNKNOWN_ERROR: return SapResultCode.UnknownError;
            case RfcResultCode.RFC_AUTHORIZATION_FAILURE: return SapResultCode.AuthorizationFailure;
            case RfcResultCode.RFC_RC_MAX_VALUE: return SapResultCode.RcMaxValue;
            default: return SapResultCode.UnknownValue;
            }
        }
    }
}
